#!/bin/bash

alias gotest="go test -coverprofile=c.out -timeout=30s -shuffle=on ./... && go tool cover -func=c.out && go tool cover -html=c.out"

alias vim="nvim"

alias sd="cd \$(find ~/dev/ws/*/ -mindepth 1 -maxdepth 1 -type d | fzf || pwd)"
