#!/bin/bash

addToPath /usr/local/go/bin
addToPath $GOPATH/bin
addToPath /usr/local/nvim-linux64/bin
addToPath $HOME/.config/scripts
addToPath $HOME/.cargo/bin
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

