#!/bin/bash

eval "$(fnm env --version-file-strategy recursive --resolve-engines --shell zsh)"

export SDKMAN_DIR="$HOME/.sdkman"
[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
