# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder "../../.", "/home/vagrant/.dotfiles"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
