# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.synced_folder "../../.", "/home/vagrant/.dotfiles", type: "rsync", rsync__exclude: ".git/"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "4"
    vb.memory = "1024"
  end
end
