# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jhcook/macos-sierra"
  config.vm.synced_folder "../../.", "/Users/vagrant/.dotfiles", type: "rsync", rsync__exclude: ".git/", group: "staff"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "4"
    vb.memory = "4096"
  end
end
